server:
  port: 8080
  
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: hu1-service
          uri: http://localhost:8001
          predicates:
            - Path=/hu1/**
        - id: hu2-service
          uri: http://localhost:8002
          predicates:
            - Path=/hu2/**
        - id: hu3-service
          uri: http://localhost:8003
          predicates:
            - Path=/hu3/**
        - id: hu4-service
          uri: http://localhost:8004
          predicates:
            - Path=/hu4/**
        - id: hu5-service
          uri: http://localhost:8005
          predicates:
            - Path=/hu5/**