spring:
  application:
    name: hu2-service
  datasource:
    url: jdbc:mysql://localhost:3306/bd_hu2-jwt
    username: root
    password: secreto
jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8002
  forward-headers-strategy: framework
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}